# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: individuart.materialize::lang.backend.reorder

# Attribute name
nameFrom: name

# Model Class name
modelClass: Individuart\Materialize\Models\Slider

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar